### ISSUE TITLE
Sometimes getting distortion on music and sound wavs

### ISSUE THREAD

**Issue by helio-frota** [finnkuusisto/TinySound#22]

**Comment by finnkuusisto** [comment]
Sorry I've been slow to respond.  Can you give a more detailed description?  It would be most helpful if you could provide some minimal reproducing code, or steps to reproduce the issue.

**Comment by SteveSmith16384** [comment]
I get exactly the same thing - sometimes.  I just tried again today and ran some simple code in Eclipse.  The first few times it was fine, but then after that the sound was like it was coming from an out-of-tune radio.  But then it sounded fine again after that.  Here's my code, but as you can see it's a virtual copy of the example code:-

```
public static void main(String args[]) {
    TinySound.init();
    //load a sound and music
    //note: you can also load with Files, URLs and InputStreams
    //Music song = TinySound.loadMusic("baboom.wav");
    Music song = TinySound.loadMusic("drum_snare2.wav");
    song.play(false);
    Sound coin = TinySound.loadSound("baboom.wav");
    //start playing the music on loop
    //play the sound a few times in a loop
    for (int i = 0; i < 2; i++) {
        coin.play();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {}
    }
    //be sure to shutdown TinySound when done
    TinySound.shutdown();
}
```

My only thought is that maybe its something to do with me stopping it before it gets to shutdown().  If I can find a way to consistently recreate the problem, I'll post again.

**Comment by SteveSmith16384** [comment]
I'm running on Linux, BTW.

**Comment by tcoxon** [comment]
This is a continuing pain for me. I've been using TinySound in my game project for a while, and there seems to be a linux-specific bug like what the OP and @SteveSmith16384 have described. After around five minutes of playing with the music on, all audio becomes noisy and distorted for a few seconds to a few minutes. To try to describe the sound, it's almost like the sound of someone walking on gravel, or like a series of small explosions, or crackling noises.

I've experienced this myself quite a lot, and it's also been reported by several other linux users in my game. It's happened on multiple Ubuntu 16.04 and Ubuntu 14.04 machines, and possibly several other flavors of Linux.

I've noticed that when this happens, the game disappears from the playback tab in pavucontrol. Normally pavucontrol looks like this while the game is running with the music on:

![image](https://cloud.githubusercontent.com/assets/165720/24323523/9e687070-116e-11e7-9e8e-628c66388a85.png)

"ALSA plug-in [java]" is the game. When the audio starts crackling, this entry disappears from the list.

The music is in OGG Vorbis 44100Hz mono format. Sounds effects are WAV PCM S16LE 44100Hz mono.

@finnkuusisto I can provide a key for the game if it would help you to reproduce it.

**Comment by tcoxon** [comment]
The issue appears to be specific to the Oracle JRE which doesn't support PulseAudio natively, only via ALSA. Ubuntu builds of OpenJDK have native PulseAudio support, and are unaffected.

Not sure whether the issue is with the JRE, or ALSA or PulseAudio, but it seems unlikely to be caused by TinySound.
