### ISSUE TITLE
High Audio Latency

### ISSUE THREAD

**Issue by serebit** [finnkuusisto/TinySound#25]
I'm playing a .au audio file, and the latency is extremely high, at about 1 second. There is a counter that goes down every time `gunshotSND.play()` is called, and the counter updates long before the sound actually plays. The sound is extremely small and there are only 32 sounds (equally small) loaded into memory at the moment. What gives?

Edit: I quit Chrome, which had a YouTube video on pause at the moment. The audio now plays at normal speed.

Edit 2: It seems that so much as having Google Chrome _open_ causes the delay.

Edit 3: Nope, it wasn't Chrome. The problem happens sporadically.

**Comment by finnkuusisto** [comment]
Hi, sorry for the exceptionally slow response. Are you certain the problem lies specifically in TinySound?  That is, can you reproduce the issue using something like the TinySound example file (https://github.com/finnkuusisto/TinySound/blob/master/example/TinySoundExample.java)?

**Comment by serebit** [comment]
I am certain, for the following reasons:
- I can reproduce the sound lag only by clicking on the window as it loads.
  Nothing else produces it, and the sound lag stays until the program is
  closed.
- No lag when using a self-written audio engine that uses javasound.

My code is here: https://www.github.com/officialexosoft/zerfall-java.

**Comment by finnkuusisto** [comment]
I have your project running on my machine, but I'm not experiencing any obvious problems.  Can you provide steps to reproduce the issue?

To clarify, I've tried clicking on the window while it's loading, but I don't experience lag.  Do I need to do something more specific?

**Comment by serebit** [comment]
Hmm. Let me try to reproduce the problem today, and I'll get back to you.

**Comment by bassem-i** [comment]
Hi, First of all, many thanks for TinySound, it is helping me very much on my bachelor thesis.

I was wondering tho,  Can i play audio with different speeds ?

just a add-on functionality i want to add to my program.
Thanks in advance.

**Comment by finnkuusisto** [comment]
You're welcome BassemMohamed.  I haven't added a playback speed feature, and unfortunately, that's probably not something I'll be adding anytime soon.  I suspect that feature requires a lot of careful thought and experimentation with sound wave interpolation that I'm not prepared to address in the near term.

**Comment by serebit** [comment]
No idea if this is still an issue, but I doubt it'll be resolved at this point anyway. Closing.
